# Generated by Django 3.1.2 on 2020-12-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oid', models.IntegerField(default=0)),
                ('order', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='fid',
        ),
        migrations.AlterField(
            model_name='fabric',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='picture',
            field=models.ImageField(upload_to='images'),
        ),
    ]
